using System.Text.RegularExpressions;

namespace McpEfReportServer.Services
{
    public class SqlGuardService
    {
        private static readonly string[] ForbiddenKeywords =
        {
            "DROP", "DELETE", "UPDATE", "INSERT",
            "ALTER", "TRUNCATE", "EXEC",
            "MERGE", "GRANT", "REVOKE", ";"
        };

        public string ValidateReadOnly(string sql)
        {
            if (string.IsNullOrWhiteSpace(sql))
                throw new Exception("Empty SQL generated by AI.");

            // ✅ STEP 1: Remove comments
            sql = RemoveSqlComments(sql);

            // ✅ STEP 2: Must start with SELECT
            if (!sql.TrimStart()
                    .StartsWith("SELECT", StringComparison.OrdinalIgnoreCase))
            {
                throw new Exception("Only SELECT queries are allowed.");
            }

            // ✅ STEP 3: Block dangerous keywords
            foreach (var keyword in ForbiddenKeywords)
            {
                if (Regex.IsMatch(sql, $@"\b{keyword}\b",
                    RegexOptions.IgnoreCase))
                {
                    throw new Exception($"Blocked unsafe SQL keyword: {keyword}");
                }
            }

            return sql;
        }

        private string RemoveSqlComments(string sql)
        {
            // Remove /* ... */ comments
            sql = Regex.Replace(
                sql,
                @"/\*.*?\*/",
                string.Empty,
                RegexOptions.Singleline);

            // Remove -- comments
            sql = Regex.Replace(
                sql,
                @"--.*?$",
                string.Empty,
                RegexOptions.Multiline);

            return sql.Trim();
        }
    }
}
